name: php

toolstack: "php:drupal"

relationships:
    database: "mysql:mysql"
    solr: "solr:solr"
    redis: "redis:redis"

web:
    document_root: "/"
    passthru: "/index.php"

disk: 2048

mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/composer": "shared:files/composer"
    "/private": "shared:files/private"

hooks:
    deploy: |
      cd public
      drush -y composer-manager install
      drush -y updatedb

crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
