name: php

toolstack: "php:drupal"

relationships:
    database: "mysql:mysql"

web:
    document_root: "/"
    passthru: "/index.php"

disk: 2048

mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/composer": "shared:files/composer"
    "/private": "shared:files/private"

hooks:
    build: |
      # Download the Drush Composer extension if it doesn't exist.
      if [ ! -d "$HOME/.drush/composer" ]; then
        drush dl composer-8.x-1.x-dev
      fi

      # Stuff to only run on local for development purposes.
      if [ -f "../../shared/local-build.sh" ]; then
        bash "../../shared/local-build.sh"
      fi
    deploy: |
      cd public
      drush cc drush
      drush -y composer-manager install
      drush -y updatedb

crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
